import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './components/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: "/manifest.json", // we are accessing our manifest file here
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />
      </head>
      <body className={`${inter.className} bg-cover`} style={{
            backgroundImage:"url('https://wallpapers-clan.com/wp-content/uploads/2023/07/fantasy-mountains-clouds-landscape-background.jpg')",
          }}>
        <header>
          <Navigation></Navigation>
        </header>
          <main>
            {children}
          </main>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js" defer></script>
      </body>
    </html>
  )
}
